# Generated by Django 5.0.2 on 2024-02-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Title')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizer')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('more', models.TextField(blank=True, null=True, verbose_name='More')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('images', models.ManyToManyField(blank=True, to='image.image', verbose_name='Images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
